stages:
  - run
image: registry1.prod1.fbc.int.lac-coloc.fr:5000/image-rsync:latest

run:
  stage: run
  script:
    - mkdir ./ssh_conf
    - mkdir ~/.ssh/
    - chmod 700 ./ssh_conf
    - echo "$SSH_ROUTER_KEY" >> ./ssh_conf/router_ed25519
    - echo "$SSH_WOL_PROD" >> ~/.ssh/ed25519
    - chmod 400 ./ssh_conf/router_ed25519
    - chmod 400 ~/.ssh/ed25519
    
    #- ansible-playbook -i inventory build-proxmox-image.yml --diff -v --private-key ~/.ssh/id_ed25519
    - rsync -az -e "ssh -i ~/.ssh/ed25519 -o StrictHostKeyChecking=no" --exclude .git . ubuntu@10.240.9.29:/home/ubuntu/wol
      #- rsync -az -e "ssh -o StrictHostKeyChecking=no" --exclude .git ./ssh_conf/router_ed25519 ubuntu@10.240.9.29:/home/ubuntu/wol/ssh_conf
    - ssh -i ~/.ssh/ed25519 -o StrictHostKeyChecking=no ubuntu@10.240.9.29 'ls'
  only:
    - master
