id: "-854544886"
name_to_mac_file: "name_to_mac.json"
path_to_private_key: "ssh_conf/router_ed25519"
router_ip: "clichy.lac-coloc.fr"
router_hostname: "wol"
bot_token: "5886610488:AAHyI2OjkmbXFigYLknvMgJ8PpOJ6JW-XBI"
ssh_password: "mlk9d0f4"

