version: '3'

services:
  backend:
    build: ./backend
    container_name: wol-backend
    network_mode: host
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: wol-frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - backend
